package com.gyleedev.domain

import com.gyleedev.githubsearch.domain.model.SearchStatus
import com.gyleedev.githubsearch.domain.model.UserFetchResult
import com.gyleedev.githubsearch.domain.model.UserModel
import com.gyleedev.githubsearch.domain.repository.GitHubRepository
import com.gyleedev.githubsearch.domain.usecase.FetchUserUseCase
import io.mockk.Runs
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.coVerifySequence
import io.mockk.just
import io.mockk.mockk
import junit.framework.TestCase.assertEquals
import kotlinx.coroutines.test.runTest
import org.junit.Before
import org.junit.Test

/*
string 을 받아서 repository 에 검색
1. Success 일 때
    - insertUser
    - upsertAccessTime
2. NoSuchUser
3. ExceedQuota
4. UnknownError
5. Exception
이 환경은 로컬에 없는 유저를 찾아서 insert 하기 때문에 항상 favorite = false, id = 0L 입니다.
accessTime 도 항상 새로운 것이 들어가기 때문에 upsert의 동작에 대해 고려할 필요가 없습니다.(autogenerated)
 */
class FetchUserTest {
    private val repository: GitHubRepository = mockk()
    private lateinit var useCase: FetchUserUseCase

    @Before
    fun setUp() {
        useCase = FetchUserUseCase(repository)
    }

    @Test
    fun `SearchResult 가 Success 일 때`() = runTest {
        val query = "android"
        val userModel = UserModel(
            id = 0L,
            name = "Android",
            login = "googleAndroid",
            followers = 300000,
            following = 800000,
            avatar = "url",
            company = "google",
            email = "google@gmail.com",
            bio = "world is changed google",
            repoCount = 80,
            createdDate = "",
            updatedDate = "",
            reposAddress = "repoUrl",
            blogUrl = "blogUrl",
            favorite = false,
        )
        val expectedValue = UserFetchResult.Success(user = userModel)
        val expectedResult = SearchStatus.SUCCESS
        coEvery { repository.fetchUser(query) } returns expectedValue
        coEvery { repository.insertUser(userModel) } just Runs
        coEvery { repository.upsertAccessTime(id = 0L, githubId = query, isRepoFetched = false) } just Runs

        val actual = useCase(query)

        assertEquals(expectedResult, actual)

        coVerifySequence {
            repository.fetchUser(query)
            repository.insertUser(userModel)
            repository.upsertAccessTime(id = 0L, githubId = query, isRepoFetched = false)
        }
    }

    @Test
    fun `SearchResult 가 NoSuchUser 일 때`() = runTest {
        val query = "android"
        val expectedValue = UserFetchResult.NoSuchUser
        val expectedResult = SearchStatus.NO_SUCH_USER
        coEvery { repository.fetchUser(query) } returns expectedValue
        coEvery { repository.insertUser(any()) } just Runs
        coEvery { repository.upsertAccessTime(id = 0L, githubId = query, isRepoFetched = false) } just Runs

        val actual = useCase(query)

        assertEquals(expectedResult, actual)

        coVerify(exactly = 1) { repository.fetchUser(query) }
        coVerify(exactly = 0) { repository.insertUser(any()) }
        coVerify(exactly = 0) { repository.upsertAccessTime(id = 0L, githubId = query, isRepoFetched = false) }
    }

    @Test
    fun `SearchResult 가 ExceedQuota 일 때`() = runTest {
        val query = "android"
        val expectedValue = UserFetchResult.ExceedQuota
        val expectedResult = SearchStatus.NEED_AUTHENTICATION
        coEvery { repository.fetchUser(query) } returns expectedValue
        coEvery { repository.insertUser(any()) } just Runs
        coEvery { repository.upsertAccessTime(id = 0L, githubId = query, isRepoFetched = false) } just Runs

        val actual = useCase(query)

        assertEquals(expectedResult, actual)

        coVerify(exactly = 1) { repository.fetchUser(query) }
        coVerify(exactly = 0) { repository.insertUser(any()) }
        coVerify(exactly = 0) { repository.upsertAccessTime(id = 0L, githubId = query, isRepoFetched = false) }
    }

    @Test
    fun `SearchResult 가 UnknownError 일 때`() = runTest {
        val query = "android"
        val expectedValue = UserFetchResult.UnknownError
        val expectedResult = SearchStatus.UNKNOWN_FAIL
        coEvery { repository.fetchUser(query) } returns expectedValue
        coEvery { repository.insertUser(any()) } just Runs
        coEvery { repository.upsertAccessTime(id = 0L, githubId = query, isRepoFetched = false) } just Runs

        val actual = useCase(query)

        assertEquals(expectedResult, actual)

        coVerify(exactly = 1) { repository.fetchUser(query) }
        coVerify(exactly = 0) { repository.insertUser(any()) }
        coVerify(exactly = 0) { repository.upsertAccessTime(id = 0L, githubId = query, isRepoFetched = false) }
    }

    @Test
    fun `SearchResult 가 Exception 일 때`() = runTest {
        val query = "android"
        val expectedException = Exception("Unknown Exception")
        val expectedResult = SearchStatus.BAD_NETWORK
        coEvery { repository.fetchUser(query) } throws expectedException
        coEvery { repository.insertUser(any()) } just Runs
        coEvery { repository.upsertAccessTime(id = 0L, githubId = query, isRepoFetched = false) } just Runs

        val actual = useCase(query)

        assertEquals(expectedResult, actual)

        coVerify(exactly = 1) { repository.fetchUser(query) }
        coVerify(exactly = 0) { repository.insertUser(any()) }
        coVerify(exactly = 0) { repository.upsertAccessTime(id = 0L, githubId = query, isRepoFetched = false) }
    }
}
